[package]
name = "polygons"
version = "0.1.2"
authors = ["Radovan Bast <bast@users.noreply.github.com>"]
description = "Computes distances to polygon edges and vertices and can check whether points are inside/outside."
license = "GPL-3.0-only"
edition = "2018"

[dependencies]
rand = "0.7.2"
rayon = "1.3.0"
