name: Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - name: Switch branch
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        which python
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build crate
      run: cargo build --verbose
    - name: Test crate
      run: cargo test --verbose
    - name: Use nightly Rust
      run: rustup override set nightly
    - name: Build crate with pyo3
      run: cargo build --release --features pyo3
    - name: Maturin publish
      run:
        maturin publish --no-sdist -u __token__ -i python --cargo-extra-args="--features pyo3"
      env:
        MATURIN_PASSWORD: ${{ secrets.PYPI_TOKEN }}
